apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy

  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot
      defaultBucket: health_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
